const celticCross = [
  [
    { name: 'hint', value: null },
    { name: 'hint', value: null, border: 'right' },
    { name: 'hint', value: null },
    { name: 'hint', value: 1 },
    { name: 'hint', value: 1 },
    { name: 'hint', value: 1 },
    { name: 'hint', value: null },
  ],
  [
    { name: 'hint', value: null, border: 'bottom' },
    { name: 'hint', value: null, border: 'right bottom' },
    { name: 'hint', value: null, border: 'bottom' },
    { name: 'hint', value: 1, border: 'bottom' },
    { name: 'hint', value: 3, border: 'bottom' },
    { name: 'hint', value: 1, border: 'bottom' },
    { name: 'hint', value: null, border: 'bottom' },
  ],
  [
    { name: 'hint', value: null },
    { name: 'hint', value: 1, border: 'right' },
    { name: 'cell', value: false },
    { name: 'cell', value: false },
    { name: 'cell', value: true },
    { name: 'cell', value: false },
    { name: 'cell', value: false },
  ],
  [
    { name: 'hint', value: 1 },
    { name: 'hint', value: 1, border: 'right' },
    { name: 'cell', value: false },
    { name: 'cell', value: true },
    { name: 'cell', value: false },
    { name: 'cell', value: true },
    { name: 'cell', value: false },
  ],
  [
    { name: 'hint', value: null },
    { name: 'hint', value: 1, border: 'right' },
    { name: 'cell', value: false },
    { name: 'cell', value: false },
    { name: 'cell', value: true },
    { name: 'cell', value: false },
    { name: 'cell', value: false },
  ],
  [
    { name: 'hint', value: null },
    { name: 'hint', value: 1, border: 'right' },
    { name: 'cell', value: false },
    { name: 'cell', value: false },
    { name: 'cell', value: true },
    { name: 'cell', value: false },
    { name: 'cell', value: false },
  ],
  [
    { name: 'hint', value: null },
    { name: 'hint', value: 3, border: 'right' },
    { name: 'cell', value: false },
    { name: 'cell', value: true },
    { name: 'cell', value: true },
    { name: 'cell', value: true },
    { name: 'cell', value: false },
  ],
];

export default celticCross;
